Vagrant.configure(2) do |config|
 config.vm.box = "bento/ubuntu-18.04"
 config.vm.hostname = "monitoring"
# config.vm.synced_folder "src/", "/var/www/html"
 config.vm.provider "virtualbox" do |vb|
 vb.memory = "1024"
 vb.cpus = "1"
 end
end